### ISSUE TITLE
User fails to authenticate when mounting a Linux Samba share

### ISSUE THREAD

**Issue by manio143** [BeyondTrust/pbis-open#104]
**Version**: 8.5.7.385
**OS/Distro**: Ubuntu server 16.04

I decided to try and setup a Samba share that would be accessible to other computers in the domain. What I have done so far is:

1. Install pbis-open
2. Join domain DEV.LOCAL
3. Setup sudo for domain admins
4. Run the `/opt/pbis/bin/samba-interop-install --install` as described in [PBIS Integration Guide](https://github.com/BeyondTrust/pbis-open/wiki/docs/PBIS_Integration_Guide.pdf) and verify `net ad testjoin` with the password from `lsa  ad-get-machine password`
5. Edit my `/etc/samba/smb.conf` (below)
6. Restart smbd
7. Attempt to mount the share on the same pc (using the domain name)

```
$ sudo mount -t cifs -o user=admin-marian,domain=dev.local //ubuntu.dev.local/Ubuntu-Public /mnt
[sudo] password for DEV\admin-marian:
Password for admin-marian@//ubuntu.dev.local/Ubuntu-Public:  *********************
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```

This produces the following in the `lsass` log (I made space around the most relevant part)

    20180220152403:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DEV.LOCAL
    20180220152403:VERBOSE:lsass:AD_CheckExpiredObject():lsass/server/auth-providers/ad-open-provider/online.c:1804: Using cache entry for sid S-1-5-21-1636718764-3450079506-1967097664-10171, updated 1275 seconds ago
    20180220152403:DEBUG:lsass:AD_OnlineCheckUserPassword():lsass/server/auth-providers/ad-open-provider/online.c:1472: Using generated UPN instead of 'admin-marian@DEV.LOCAL'
    20180220152403:VERBOSE:lsass:AD_CacheGroupMembershipFromPac():lsass/server/auth-providers/ad-open-provider/online.c:1041: Updating user group membership for uid 589834171 with PAC information
    20180220152403:VERBOSE:LwKrb5GroupMembershipFromPac():lwadvapi/threaded/lwkrb5.c:2143: rid 10171's #0 PAC group membership is S-1-5-21-1636718764-3450079506-1967097664-512
    20180220152403:VERBOSE:LwKrb5GroupMembershipFromPac():lwadvapi/threaded/lwkrb5.c:2143: rid 10171's #1 PAC group membership is S-1-5-21-1636718764-3450079506-1967097664-513
    20180220152403:VERBOSE:LwKrb5GroupMembershipFromPac():lwadvapi/threaded/lwkrb5.c:2143: rid 10171's #2 PAC group membership is S-1-5-21-1636718764-3450079506-1967097664-10146
    20180220152403:VERBOSE:LwKrb5GroupMembershipFromPac():lwadvapi/threaded/lwkrb5.c:2151: rid 10171's #0 PAC resource group membership is S-1-5-21-1636718764-3450079506-1967097664-572
    20180220152403:VERBOSE:LwKrb5GroupMembershipFromPac():lwadvapi/threaded/lwkrb5.c:2160: rid 10171's #0 PAC extra membership is S-1-18-1 (attributes = 0x00000007)
    20180220152403:VERBOSE:lsass:AD_CacheUserRealInfoFromPac():lsass/server/auth-providers/ad-open-provider/online.c:1169: Updating user for uid 589834171 information from from one-way trusted domain with PAC information
    20180220152403:DEBUG:lsass:LsaUmpAddUser():lsass/server/auth-providers/ad-open-provider/lsaum_p.c:1220: LSA User Manager - requesting user addition 589834171
    20180220152403:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DEV.LOCAL
    20180220152403:VERBOSE:lsass-ipc:lwmsg_peer_task_handle_assoc_error():lwmsg/src/peer-task.c:625: (session:342d5629f50f24db-334c3ecec858729e) Dropping: LWMSG_STATUS_PEER_CLOSE
    20180220152403:VERBOSE:lsass:LsaSrvIpcCheckPermissions():lsass/server/api/ipc_state.c:79: Permission granted for (uid = 0, gid = 589824513, pid = 3660) to open LsaIpcServer
    20180220152403:VERBOSE:lsass-ipc:lwmsg_peer_log_accept():lwmsg/src/peer-log.c:230: (session:cfcfda5184f5f5ad-b68cb8b20282ba3f) Accepted <local euid:0 egid:589824513 pid:3660>
    20180220152403:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:VERBOSE:lsass-ipc:lwmsg_peer_task_handle_assoc_error():lwmsg/src/peer-task.c:625: (session:cfcfda5184f5f5ad-b68cb8b20282ba3f) Dropping: LWMSG_STATUS_PEER_CLOSE
    20180220152403:VERBOSE:lsass:LsaSrvIpcCheckPermissions():lsass/server/api/ipc_state.c:79: Permission granted for (uid = 0, gid = 589824513, pid = 3660) to open LsaIpcServer
    20180220152403:VERBOSE:lsass-ipc:lwmsg_peer_log_accept():lwmsg/src/peer-log.c:230: (session:70564d8962a2c567-c57ee06ec060434e) Accepted <local euid:0 egid:589824513 pid:3660>
    20180220152403:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DEV.LOCAL
    20180220152403:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DEV.LOCAL
    20180220152403:VERBOSE:lsass:AD_CheckExpiredObject():lsass/server/auth-providers/ad-open-provider/online.c:1804: Using cache entry for sid S-1-5-21-1636718764-3450079506-1967097664-10171, updated 0 seconds ago
    20180220152403:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DEV.LOCAL
    20180220152403:VERBOSE:lsass:AD_CheckExpiredObject():lsass/server/auth-providers/ad-open-provider/online.c:1804: Using cache entry for sid S-1-5-21-1636718764-3450079506-1967097664-10171, updated 0 seconds ago
    20180220152403:VERBOSE:lsass-ipc:lwmsg_peer_task_handle_assoc_error():lwmsg/src/peer-task.c:625: (session:70564d8962a2c567-c57ee06ec060434e) Dropping: LWMSG_STATUS_PEER_CLOSE
    20180220152403:VERBOSE:lsass:LsaSrvIpcCheckPermissions():lsass/server/api/ipc_state.c:79: Permission granted for (uid = 0, gid = 589824513, pid = 3660) to open LsaIpcServer
    20180220152403:VERBOSE:lsass-ipc:lwmsg_peer_log_accept():lwmsg/src/peer-log.c:230: (session:e34f0874968e1b73-3c6a8cfa6f3b0ebc) Accepted <local euid:0 egid:589824513 pid:3660>
    20180220152403:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152403:VERBOSE:lsass-ipc:lwmsg_peer_task_handle_assoc_error():lwmsg/src/peer-task.c:625: (session:e34f0874968e1b73-3c6a8cfa6f3b0ebc) Dropping: LWMSG_STATUS_PEER_CLOSE
    20180220152403:VERBOSE:lsass:LsaSrvIpcCheckPermissions():lsass/server/api/ipc_state.c:79: Permission granted for (uid = 0, gid = 589824513, pid = 3660) to open LsaIpcServer
    20180220152403:VERBOSE:lsass-ipc:lwmsg_peer_log_accept():lwmsg/src/peer-log.c:230: (session:b9321a0836cd1a78-75fff09804cc9a89) Accepted <local euid:0 egid:589824513 pid:3660>
    20180220152403:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DEV.LOCAL
    20180220152403:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DEV.LOCAL
    20180220152403:VERBOSE:lsass:AD_CheckExpiredObject():lsass/server/auth-providers/ad-open-provider/online.c:1804: Using cache entry for sid S-1-5-21-1636718764-3450079506-1967097664-10171, updated 0 seconds ago
    20180220152403:VERBOSE:lsass-ipc:lwmsg_peer_task_handle_assoc_error():lwmsg/src/peer-task.c:625: (session:b9321a0836cd1a78-75fff09804cc9a89) Dropping: LWMSG_STATUS_PEER_CLOSE
    20180220152407:VERBOSE:lsass:LsaSrvIpcCheckPermissions():lsass/server/api/ipc_state.c:79: Permission granted for (uid = 0, gid = 0, pid = 3667) to open LsaIpcServer
    20180220152407:VERBOSE:lsass-ipc:lwmsg_peer_log_accept():lwmsg/src/peer-log.c:230: (session:a9ec077773f991d6-16a809745dcbd8c9) Accepted <local euid:0 egid:0 pid:3667>
    20180220152407:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DEV.LOCAL
    20180220152407:DEBUG:netlogon:LWNetTransactGetDCName():netlogon/client/ipc_client.c:250: Error: 1355
    20180220152407:DEBUG:netlogon:LWNetGetDCNameExt():netlogon/client/dcinfo.c:133: Error: 1355
    20180220152407:DEBUG:netlogon:LWNetTransactGetDCName():netlogon/client/ipc_client.c:250: Error: 1355
    20180220152407:DEBUG:netlogon:LWNetGetDCNameExt():netlogon/client/dcinfo.c:133: Error: 1355
    20180220152407:VERBOSE:lsass-ipc:lwmsg_peer_task_handle_assoc_error():lwmsg/src/peer-task.c:625: (session:a9ec077773f991d6-16a809745dcbd8c9) Dropping: LWMSG_STATUS_PEER_CLOSE
    20180220152407:VERBOSE:lsass:LsaSrvIpcCheckPermissions():lsass/server/api/ipc_state.c:79: Permission granted for (uid = 0, gid = 0, pid = 3667) to open LsaIpcServer
    20180220152407:VERBOSE:lsass-ipc:lwmsg_peer_log_accept():lwmsg/src/peer-log.c:230: (session:cf951edf06abb142-156f336c7e7dc308) Accepted <local euid:0 egid:0 pid:3667>
    20180220152407:DEBUG:LwKrb5SetThreadDefaultCachePath():lwadvapi/threaded/lwkrb5.c:480: Switched gss krb5 credentials path from <null> to FILE:/var/lib/pbis/krb5cc_lsass.DEV.LOCAL

    20180220152407:DEBUG:lsass:NtlmServerAcquireCredentialsHandle():lsass/server/ntlm/acquirecreds.c:103: Error code: 40506 (symbol: LW_ERROR_NO_CRED)
    20180220152407:DEBUG:lsass:NetrSamLogonNetworkEx():lsass/client/rpc/netlogon/netr_samlogonex.c:342: Error at /builder/src-git/Platform/src/linux/lsass/client/rpc/netlogon/netr_samlogonex.c:342 [code: C000006D]
    20180220152407:DEBUG:lsass:AD_NetlogonAuthenticationUserEx():lsass/server/auth-providers/ad-open-provider/adnetapi.c:1875: NetrSamLogonNetworkEx() failed with 3221225581 (0xc000006d) (symbol: 'STATUS_LOGON_FAILURE') while authenticating user 'dev.local\admin-marian'
    20180220152407:DEBUG:lsass:AD_NetlogonAuthenticationUserEx():lsass/server/auth-providers/ad-open-provider/adnetapi.c:1938: Error code: 40082 (symbol: LW_ERROR_LOGON_FAILURE)
    20180220152407:DEBUG:lsass:LsaDmConnectDomain():lsass/server/auth-providers/ad-open-provider/lsadm.c:3786: Error code: 40082 (symbol: LW_ERROR_LOGON_FAILURE)
    20180220152407:DEBUG:lsass:AD_AuthenticateUserEx():lsass/server/auth-providers/ad-open-provider/provider-main.c:1773: Error code: 40082 (symbol: LW_ERROR_LOGON_FAILURE)
    20180220152407:DEBUG:lsass:LsaSrvAuthenticateUserEx():lsass/server/api/auth.c:345: Error code: 40082 (symbol: LW_ERROR_LOGON_FAILURE)
    20180220152407:ERROR:lsass:LsaSrvAuthenticateUserEx():lsass/server/api/auth.c:402: Failed to authenticate user (name = 'admin-marian') -> error = 40082, symbol = LW_ERROR_LOGON_FAILURE, client pid = 3667

    20180220152407:VERBOSE:lsass-ipc:lwmsg_peer_task_handle_assoc_error():lwmsg/src/peer-task.c:625: (session:cf951edf06abb142-156f336c7e7dc308) Dropping: LWMSG_STATUS_PEER_CLOSE
    20180220152407:VERBOSE:lsass:LsaSrvIpcCheckPermissions():lsass/server/api/ipc_state.c:79: Permission granted for (uid = 0, gid = 589824513, pid = 3660) to open LsaIpcServer
    20180220152407:VERBOSE:lsass-ipc:lwmsg_peer_log_accept():lwmsg/src/peer-log.c:230: (session:752608d1caf7ca28-f1f9c8e7320b60e2) Accepted <local euid:0 egid:589824513 pid:3660>
    20180220152407:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152407:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152407:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152407:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152407:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152407:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152407:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152407:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152407:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152407:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152407:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152407:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152407:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152407:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152407:DEBUG:lwreg:RegTransactGetValueW():lwreg/client/clientipc.c:809: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152407:DEBUG:lwreg:LwNtRegGetValueA():lwreg/client/regntclient.c:793: Status: LW_STATUS_OBJECT_NAME_NOT_FOUND = 0xC0000034 (-1073741772)]
    20180220152407:VERBOSE:lsass-ipc:lwmsg_peer_task_handle_assoc_error():lwmsg/src/peer-task.c:625: (session:752608d1caf7ca28-f1f9c8e7320b60e2) Dropping: LWMSG_STATUS_PEER_CLOSE

`/etc/samba/smb.conf`:
```
[global]
        realm = DEV.LOCAL
        server string = %h server (Samba, Ubuntu)
        server role = standalone server
        security = ADS
        map to guest = Bad User
        obey pam restrictions = Yes
        pam password change = Yes
        passwd program = /usr/bin/passwd %u
        passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
        unix password sync = Yes
        syslog = 0
        log file = /var/log/samba/log.%m
        max log size = 1000
        client max protocol = SMB3
        client min protocol = SMB2
        machine password timeout = 0
        dns proxy = No
        usershare allow guests = Yes
        panic action = /usr/share/samba/panic-action %d
        idmap config * : backend = tdb


[printers]
        comment = All Printers
        path = /var/spool/samba
        create mask = 0700
        printable = Yes
        browseable = No


[print$]
        comment = Printer Drivers
        path = /var/lib/samba/printers


[Ubuntu-Public]
        path = /home/public
        read only = No
```

I tried reading into the code what might be the culprit, but I was unable to figure it out. As you can see I have successfully connected to the domain as I'm logged on as a domain user. Maybe I missed some crutial step?

**Comment by rbest-bt** [comment]
What are the file permissions of /home/public ?

Back up your smb.conf and then try to trim down your global settings. See if this works for you:
>[global]
	workgroup = DEV
	realm = DEV.LOCAL
	security = ADS
	log file = /var/log/samba/log.%m
	max log size = 1000
	machine password timeout = 0
	idmap config * : backend = tdb
