### ISSUE TITLE
PBIS authentication stops working on Ubuntu Server 16.04.2

### ISSUE THREAD

**Issue by pfcapp** [BeyondTrust/pbis-open#53]
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu server 16.04.2
**Issue/Impact**: [lsass] Error: Failed to refresh machine TGT for

Keep getting the following error after a week or two on one machine:

[lsass] Error: Failed to refresh machine TGT for xxxxxxxx

Users can't login at this point.

Only way to fix this that I have found is to restart lwsmd and then rejoin the domain.  Will work for another week or two and then need to repeat those steps.

Have another server with same setup that has no problems.

**Comment by rbest-bt** [comment]
Try setting lsass to debug just before the machine password expires to see what the errors are. If you don't want to wait, set it to reset each hour:
`/opt/pbis/bin/config MachinePasswordLifespan 3600`

Also a packet capture could help identify what failed.

**Comment by pfcapp** [comment]
It seemed to work ok for a while even with the shortened expiration time but then I got the following and it is broken again:

20170828193458:VERBOSE:lsass:ADRefreshMachineTGT():lsass/server/auth-providers/ad-open-provider/machinepwd.c:548: Refreshing machine TGT
20170828193458:VERBOSE:lsass:ADSyncMachinePasswordThreadRoutine():lsass/server/auth-providers/ad-open-provider/machinepwd.c:377: Machine TGT was refreshed successfully for XXXXXXXX


20170830010458:DEBUG:lsass:LsaMachineChangePassword():lsass/server/auth-provider
s/ad-open-provider/join/join.c:3175: Error code: 86 (symbol: ERROR_INVALID_PASSW
ORD)
20170830010458:ERROR:lsass:ADChangeMachinePasswordInThreadLock():lsass/server/au
th-providers/ad-open-provider/machinepwd.c:214: Error: Failed to change machine
password for XXXXXXXXXXXXXXXX (error = 86)
20170830010458:DEBUG:lsass:ADChangeMachinePasswordInThreadLock():lsass/server/au
th-providers/ad-open-provider/machinepwd.c:221: Error code: 86 (symbol: ERROR_IN
VALID_PASSWORD)
20170830010458:VERBOSE:lsass:ADRefreshMachineTGT():lsass/server/auth-providers/ad-open-provider/machinepwd.c:548: Refreshing machine TGT
20170830010458:WARNING:LwTranslateKrb5Error():lwadvapi/threaded/lwkrb5.c:874: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -1765328360 (Message: Preauthentication failed)
20170830010458:DEBUG:LwKrb5InitializeCredentials():lwadvapi/threaded/lwkrb5.c:576: [LwKrb5InitializeCredentials() /builder/src-git/Platform/src/linux/lwadvapi/threaded/lwkrb5.c:576] Error code: 40022 (symbol: <null>)
20170830010458:DEBUG:lsass:ADRefreshMachineTGT():lsass/server/auth-providers/ad-open-provider/machinepwd.c:567: Error code: 40022 (symbol: LW_ERROR_PASSWORD_MISMATCH)

**Comment by rbest-bt** [comment]
Is there a chance you have multiple computers joined with the same name?

**Comment by aadityabagga** [comment]
Hi,

I faced similar issue when trying to login, this was in the logs:

_in /var/log/syslog_:
~~~~
Nov 17 12:34:26 tec-no002 lsass: [lsass] Error: Failed to change machine password for SERVER.LAN (error = 86)
Nov 17 12:34:26 tec-no002 lsass: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -1765328360 (Message: Preauthentication failed)
Nov 17 12:34:26 tec-no002 lsass: [lsass] Error: Failed to refresh machine TGT for SERVER.LAN (error = 40022)
~~~~

_in /var/log/auth.log_:
~~~~
Nov 17 12:27:03 tec-no002 lightdm: [lsass-pam] [module:pam_lsass]pam_sm_authenticate error [login:SERVER\aaditya][error code:40022]
~~~~

Am trying to debug it and will post more info after finding out what the issue is.

**Comment by rbest-bt** [comment]
Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge
